version: '3.8'

services:
  web:
    image: manelfideles/save-it:latest
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped